### ISSUE TITLE
Into & From implementations

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#160]
It'd be nice if there were Into and From implementation between arrays, matrices and other objects. This'd be more intuitive than having to go to the online doc and search for the exact function name.

**Comment by sebcrozet** [comment]
I've made 58000e48383e0285da5863321195b4652a7f8c23 to address this issue by implementing `AsRef`, `AsMutRef` and `From` for `Mat*`, `Vec*`, and `Quat`. Though it does not implement the `Into` trait. The implementations are made for pointers because one may switch between the array and Vec/Mat/Quat representations for free (i-e without any copy). To obtain an actual copy, one can still use `.clone()` or the `*` operator on the reference returned.

I'm still unsure whether adding by-copy implementations would be useful. Unfortunately, we cannot perform partial moves on arrays, so an e.g. `impl<N> From<[N; 3]> for Vec3<N>` would require `N` to implement `Clone`, which is unfortunate (but, not very restrictive as N will almost always be a scalary, Copy-able type).

**Comment by moll** [comment]
@sebcrozet: Might be a silly beginner question, but how you use the `from` functions with arrays?

I'm giving them an inline array reference (`Matrix4::from(&[...])`), yet am getting the following type error:
```
 expected `nalgebra::structs::matrix::Matrix4<_>`,
    found `&[[f32; 4]; 4]`
(expected struct `nalgebra::structs::matrix::Matrix4`,
    found &-ptr) [E0308]
```

This is with Rust v1.8.0 and Nalgebra 0.8.0. Thanks!

**Comment by sebcrozet** [comment]
Because `From` is implemented for `&Matrix4` (to perform a shallow conversion) instead of `Matrix4`, you have to do something like this:

```rust
let mat: &Matrix4<f64> = From::from(&[ ... ]);
```

I realize that's not very ergonomic though… so it would be useful to add an implementation of `From<[[N; 4]; 4> for Matrix4<N>` as well in a future release of nalgebra.

**Comment by sebcrozet** [comment]
@moll You will now be able to do what you intended (`Matrix4::from(&[...])`) with the version 0.8.1 of nalgebra!

**Comment by moll** [comment]
Thanks!

**Comment by mathstuf** [comment]
I'm interested in an instance of `From<Matrix4> for [[f32; 4]; 4]` (basically the opposite of the existing ones). Would that be acceptable?

**Comment by sebcrozet** [comment]
That would be acceptable. Though, keep in mind that because matrices in `nalgebra` are column-major (this will be customizable in the future), the input array should be in column-major order as well, i.e., each inner array `[f32; 4]` is a column of a matrix.

**Comment by sebcrozet** [comment]
Sorry, I meant: the **output** array should be in column-major order.

**Comment by mathstuf** [comment]
It looks like that's what all the graphics pipelines want anyways, so that's fine with me :) .

**Comment by jpernst** [comment]
I was about to open an issue for this until I saw there already was one. My library has a function that attempts to take any Vector3-like struct by means of accepting anything that implements `Into<[f32; 3]>`, this works for cgmath, but I'd like to also be compatible with nalgebra since it's a popular choice in the rust gamedev scene. Are these conversions viable to implement given the new 0.11 redesign?

**Comment by sebcrozet** [comment]
Yes ! That's still possible after the redesign but only for matrice that own their data buffer (i.e not for slices). I've added conversions to arrays for matrices and vectors of dimensions 1 to 6 in the version 0.11.1.
