### ISSUE TITLE
Poll: rename everything to use full names, e.g., `Iso3` becomes `Isometry3`.

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/nalgebra#176]
Currently, `nalgebra` tends to use 3-letter or 4-letter names for all the algebraic entities (e.g. Vec, Mat, Rot, Quat, etc.) Unfortunately, this naming convention is not very (not _at all_ actually) explicit for some structures like (direct) isometries `Iso` and the recently added similarity transformations `Sim`.

Thus, I now think that full names would be much better as they would make the code more readable, and would help users to find what he wants on the documentation. For example, I doubt that anyone reading the documentation would guess at first glance that `Sim` is a transformation.

So I would like to know if current users would be in favor of full names instead of the current ones! Of course, if the majority seems to agree with this change, it would break every single project using `nalgebra`.

**Comment by aepsil0n** [comment]
I am in favour of this, as it makes the code more readable. The breaking change is something that cargo can deal with, I think, as long as you bump the major version number. (Of course, not when people depend on `"*"`.)

**Comment by bjz** [comment]
I don't currently use nalgebra, but I would support this – to be honest, the abbreviations in the methods and types are part of the reason I continued development on cgmath. There is also the issue that `Vec` is something special in the `std`.

**Comment by Binero** [comment]
Yes.

**Comment by sebcrozet** [comment]
Alright, I am going to rename everything for the version 0.7.0!

**Comment by sebcrozet** [comment]
Actually, this will be for the version 0.8.0. I had to bump it to 0.7.0 already because of #179 .

**Comment by arturoc** [comment]
too late i guess but i had just had a surprise when updating a project and found out that the names had changed. the abbreviations were one of the reasons i chose nalgebra over cgmath. i'm mostly using nalgebra for opengl stuff and it makes so much sense to have Vec3 or Mat4 since that's the same naming that glsl uses also glm the de-facto c++ library for graphics math. 

Rust itself also uses a lot of abbreviations, like Vec over Vector or Rc, Ref... so it would seem that abbreviations are somehow more idiomatic

also this classes are usually used a lot of times if you are creating vectors of vec so having to type the full thing is pretty tedious and doesn't really add much in my opinion. 

i even use some utility functions like vec2, vec3, pnt2... so i can quickly create objects without having to call the full class + new, so Vec2::new(x,y)  -> vec2(x,y)

**Comment by Jonesey13** [comment]
@arturoc said pretty much all of my thoughts on this. 

I think that as long as there's no ambiguity it's a lose-lose situation to make the names more verbose. For one of my projects I have been forced to lock onto 0.7.0 until I can find an alternative.

**Comment by Moredread** [comment]
@arturoc 'Another lib does it this way' is not a good argument in my opinion. Just look at FORTRAN style names, e.g. in BLAS http://www.netlib.org/blas/#_reference_blas_version_3_6_0

I don't think that you can say that shortend names are more idiomatic. When looking e.g. at the module list in std many names could be shorter. I even find it a bit confusing at times, that there is no consistent naming style. E.g. Vec is short, the Map subtypes verbosly named.

@Jonesey13 What is the issue with longer names? The conversion effort, or does it make the code more difficult to read?

Working with numerical simulation code in my opinion verbose names really helps the understanding of the algorithm I'm reading. (E.g. is 'conv' in the code a convolution, or is it a conversion?) In the context of a library just one might make sense and is the obvious choice, but when combing several libs and concepts in different domains, it can become confusing. For Matrix, Vector etc. it might be obvious, but for making code easier to read and for consistency I'm in favour for clearer (and that often means more 'verbose') names.

**Comment by arturoc** [comment]
i guess for people coming from and using the library for opengl / graphics, names like vec and mat make the most sense since that's what we are used to and what we use most of the time. the code for graphics programming is full of vec this mat that :) so it makes it much faster to read and write. also sometimes you write something to run on the cpu and if the type names are the same it's really straight forward to translate to a shader

probably for people with a more scientific / math background longer names make more sense since that's what libraries in that field might use i guess.

in rust as i see it the most commonly used objects have very abbreviated names like Vec or Rc, Arc... while names that might be used less often have more descriptive names like HashMap or TreeMap.... 

I guess that could be a good compromise here, have the most commonly used objects have short names like Vec3 or Mat4 while other objects and mostly traits could have longer names. perhaps it could just be aliased types but i would love if the methods referring to those types also had shorter names like to_vec() instead of to_vector() or to_pnt() instead of to_point()

as i see it, those types are used so often (at least in graphics programming) that making them longer or more explicit doesn't really add much clarity.

**Comment by Jonesey13** [comment]
* Yes the conversion issue is arguably the greatest problem.
  *  This is probably the biggest breaking change I have seen in a library to date.
  *  As I have been using this library quite extensively there will be quite a lot of added bloat to the code after this change (and I can't just declare renames in some header file like I would normally do in C++ to keep things concise)

* Regarding the renames themselves
  * Some of them _are_ good in my opinion 
    * `orig` is very misleading in my opinion and `origin` is definitely an improvement (don't know why you'd need it when you can just use zero but that's a separate issue)
  * The majority of renames seem unnecessary to me
    * Nobody should be too surprised by what terms like Vec2 and Mat2 mean, and are certainly not misleading.
    * If this is unclear then this is the role of the documentation, not the variable names

**Comment by Binero** [comment]
I'm an advocate for consistency. Either use full names everywhere or
nowhere.

**Comment by paholg** [comment]
> (and I can't just declare renames in some header file like I would normally do in C++ to keep things concise)

Why not?

Something like this in your crate root aught to do it:

```rust
extern crate nalgebra as nalgebra_long;

mod nalgebra {
    pub use nalgebra_long::Vector3 as Vec3;
    // ...
}
```

Then, a `use nalgebra::Vec3;` in any of your submodules should work fine.

**Comment by Jonesey13** [comment]
Thanks that's a pretty nice workaround @paholg!

**Comment by paholg** [comment]
Even better, I just learned that it's valid to rename multiple imports on the same line.

```rust
pub use nalgebra_long::{Vector3 as Vec3, Vector4 as Vec4, Matrix3 as Mat3, Matrix4 as Mat4};
```

is perfectly valid syntax.
