### ISSUE TITLE
Cannot convert from NumVector to NumPoint

### ISSUE THREAD

**Issue by Limeth** [sebcrozet/nalgebra#190]
`NumPoint` implements the `PointAsVector` trait, so I can use `point.to_vector()`, but I cannot convert from `NumVector` to `NumPoint`, because there is no `VectorAsPoint`/`vector.to_point()`.

Possibly related: #160

**Comment by sebcrozet** [comment]
One way to "convert" a vector to a point is to do: `na::origin::<ThePointType>() + vector`.

Operations on vectors never depend on the definition of a point type, especially when vectors are just seen as elements of some (implicit) vector space with no geometrical interpretation. Thus, there is no reason for a vector to be aware of the point type through a `VectorAsPoint` trait. (Also, defining such a trait would prevent multiple point types to be associated to the same vector type on `PointAsVector`).

On the other hand, going the other way round (making points aware of the vector type through `PointAsVector`) is fine because points intrinsically depend on vectors for, e.g., subtractions.
