### ISSUE TITLE
Remove unused arguments in static functions

### ISSUE THREAD

**Issue by Limeth** [sebcrozet/nalgebra#198]
Some functions have unused arguments. Why not get rid of them? http://nalgebra.org/doc/src/nalgebra/src/traits/operations.rs.html#153-171

**Comment by sebcrozet** [comment]
The unused arguments are for type inference. You can't just call `ApproxEq::approx_epsilon()` because the compiler would not know which implementation of `ApproxEq` you are referring to.

Ideally, we would want to write something like `ApproxEq::<T>::approx_epsilon()` to tell the compiler that we want the epsilon for the type T, but this is not permitted in Rust. Unused argument wrapped by an `Option` is the common workaround: `ApproxEq::approx_epsilon(None::<T>)`.

**Comment by phaazon** [comment]
`<T as ApproxEq>::approx_epsilon()` is well permitted.

**Comment by sebcrozet** [comment]
Oh, I didn't know about that one! I wonder if it was permitted a while ago, before Rust 1.0... Anyway, in that case unused argument can be removed!

**Comment by phaazon** [comment]
It was added in rust 1.0! :) I’ll write the patch if I find spare time today :)

**Comment by phaazon** [comment]
The tests need to be fixed, but all the code is there.

**Comment by phaazon** [comment]
(fuck up with the config, I just update the commit upstream, I hate to do that). The code is written for the patch. Just missing is the test code.
