### ISSUE TITLE
impl Default for types

### ISSUE THREAD

**Issue by purpleposeidon** [sebcrozet/nalgebra#201]
Useful for generic programming. In particular I need them for Quaternion & UnitQuaternion; returning Self::one() is the obvious implementation there.

**Comment by sebcrozet** [comment]
I would be interested to know more about your use-case. In particular, why can't your generic code require the `One` trait instead of `Default`?

I agree that `Self::one()` would be the obvious implementation for unit quaternions, rotations, similarities, and isometries. On the other hand, it is **not** the obvious choice for quaternions, raw matrices and vectors: `Self::zero()`, the additive neutral element, could also be chosen.

**Comment by purpleposeidon** [comment]
The use case is initializing arrays used in containers; eg enums won't implement `One`, but they might `Default`. There might be a better way of doing this, like copying from some initializer value.

**Comment by sebcrozet** [comment]
Yes, copying from an initialiser value seems more suitable. I'm not fond of `Default` in general because it does not hold any useful semantic and its meaning might be ambiguous some times (like the for matrices, vectors, etc.)

**Comment by sebcrozet** [comment]
This will not be added because the semantics of `Default` would be ambiguous. Closing.
