### ISSUE TITLE
Can you explain why inverse cannot be computed ?

### ISSUE THREAD

**Issue by Kerollmops** [sebcrozet/nalgebra#214]
This matrice has an inverse:
```
[-0.34727043,         0.00000005397217,   -0.000000000000003822135, -0.000000000000003821371]
[0,                   -0.000000026986084, -1.0001999,               -1]
[0.000000030359345,   0.61736965,         -0.000000043720128,       -0.00000004371139]
[-0.0000000029144975, -0.05926739,        3.8007796,                4]
```

And this one doesn't:
```
[-0.34727043,         0.00000005397217,   -0.000000000000003822135, -0.000000000000003821371]
[0,                   -0.000000026986084, -1.0001999,               -1]
[0.000000030359345,   0.61736965,         -0.000000043720128,       -0.00000004371139]
[-0.0000000029448568, -0.05988476,        3.8007796,                4]
```

**Comment by Kerollmops** [comment]
I looked at your code and find [mathportal - gauss jordan](http://www.mathportal.org/linear-algebra/matrices/gauss-jordan.php) that explain how Gauss-Jordan elimination works, but can't explain this...

(float underflow ?)

**Comment by aepsil0n** [comment]
float underflow seems to be the most likely explanation for what is happening here. I know it's been a while, since this has been reported. Did you debug this to find out, where in the algorithm the decision is made that this matrix is not invertible by any chance?

I would assume that the very slight variation there leads to something becoming 0, that wasn't before and thereby changes whether the matrix is invertible or not.

Nonetheless, I would argue that working around the limitations of floating-point precision is out of scope for `nalgebra` (unless the algorithm is generally ill-conditioned, which I do not believe to be the case here). Therefore I am going to close this issue for now.
