### ISSUE TITLE
Renaming component_div_mut into component_div_assign ?

### ISSUE THREAD

**Issue by Kerollmops** [sebcrozet/nalgebra#226]
The [`component_div_mut`](http://nalgebra.org/rustdoc/nalgebra/core/struct.Matrix.html#method.component_div_mut) can be renamed `component_div_assign` to keep consistency with the rust standard [MulAssign](https://doc.rust-lang.org/std/ops/trait.MulAssign.html) ops trait.
What do you think about that ? I can make the "probably big" PR 😄

**Comment by Kerollmops** [comment]
In fact it seems all `*_mut` methods can be renamed `*_assign`.

**Comment by sebcrozet** [comment]
Well I don't know what the convention is in that case. For example [rulinalg](https://github.com/AtheMathmo/rulinalg) seems to be using `_in_place` as a suffix for methods that perform in-place oprations. If there is no specific convention (besides the operator-assignement traits), I'd like to keep `_mut` because it is shorter and to avoid a breaking change.

Also, some methods like `.iter_mut()` or `.get_unchecked_mut()` that just return a mutable reference/pointer should not be renamed `.iter_assign()`.

**Comment by aepsil0n** [comment]
I think the similarity to assignment operators is a valid point. After all, we assume that people mostly use the standard matrix multiplication instead of the component-wise variant, but it could easily be implemented the other way around. So in some way, they are just two valid ways to perform multiplication/division on a matrix. In my opinion, it makes sense to signal that similarity by using similar method names.

Regarding name length, I don't think 3 characters are going to make a big dent, given how long the name is already. After all, code is generally read more often than it is written.

But I agree that the change is not worth breaking backwards-compatibility. So how about having both names `_assign` and `_mut`? We can deprecate the `_mut` form using the feature from [RFC 1270](https://github.com/rust-lang/rfcs/blob/master/text/1270-deprecation.md) and keep it around for a while.

**Comment by sebcrozet** [comment]
Yes, I think that transitioning from `_mut` to `_assign` using `#[deprecated]` is the right way to go here.

**Comment by aepsil0n** [comment]
Cool, then let's introduce the new method names as aliases first.

@Kerollmops do you still want to work on a PR for this?

**Comment by Kerollmops** [comment]
No, I can't work on this at the moment :)

**Comment by aepsil0n** [comment]
Okay, no worries. That is pretty much the plan.
