### ISSUE TITLE
Type Casting

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#235]
Is there an easy way to go from, say, `Point2<i32>` to `Point2<f32>`. There doesn't seem a way to do this atm that doesn't involve more than a function call.

If there is no such way to do it, I'd be happy to implement a `From` to cast between types.

**Comment by sebcrozet** [comment]
You should be able to use `let float_point = nalgebra::convert(int_point)`.

**Comment by Binero** [comment]
It seems the reverse is actually not possible. How would this be achieved?

**Comment by sebcrozet** [comment]
The reverse is possible but may fail (for example if a value being converted is `NaN`). So, instead of `::convert`, you have to use `nalgebra::try_convert` which returns an `Option<…>`. If you don't care about special float values, you can use `nalgebra::convert_unchecked` which will always succeed and just performs the cast without checking for `Inf`/`NaN`. (`convert_unchecked` is unsafe because this kind of conversion  without checks can lead to crashes for other, more complicated types.)

**Comment by aepsil0n** [comment]
I made an attempt to improve how this feature can be discovered in the API documentation by having the function documentations refer to each other for `convert` and `try_convert`. Let's hope this will inform future users better.

Closing, as the issue appears to be resolved otherwise.
