### ISSUE TITLE
Suggestion: Don't use approximate determinant check to determine invertibility

### ISSUE THREAD

**Issue by Andlon** [sebcrozet/nalgebra#244]
The current [try_inverse()](https://github.com/sebcrozet/nalgebra/blob/1471031ac45e8b69558259a44726087a3383e511/src/core/inverse.rs#L57) implementation for 2x2 and 3x3 matrices attempts to use an approximate comparison with the determinant as a check for whether the matrix is invertible. Unfortunately, this is not a reliable way to determine if a matrix is invertible, and will readily refuse to invert perfectly invertible matrices.

Consider the following 3x3 matrix:

```
[ a   0   0 ]
[ 0   a   0 ]
[ 0   0   a ]
```

where `a` is some arbitrary non-zero constant. This matrix is as invertible as it gets: it is diagonal and has a condition number of 1, and there are no numerical issues associated with either inverting it or solving for a given right-hand side. However, the determinant of this matrix is a<sup>3</sup>. If, say, `a = 1e-6`, this means that its determinant is `1e-18`, which will fail the relative test currently used.

What is the correct way to determine if the matrix is invertible? Well, in this case, your best bet is probably to just check if the determinant is exactly zero. If it is not, assume it is invertible at the cost of some possible numerical instability. Anything else would require some rigorous numerical analysis and possible non-negligible runtime overhead for additional checks.

I'm running into problems for my simple game because I have some objects with significantly differing masses, which leads to inertia tensors of similar form as the example I posted.

I'd be willing to make a PR for the change, but it of course presumes that we can agree on the remedy.

**Comment by sebcrozet** [comment]
Another issue with the current implementation is that 2D and 3D matrix inversions fail if their determinant is smaller than some threshold, while higher-dimensional matrice won't (because they use Gauss-Jordan elimination which won't fail unless the rows are exactly linearly dependent). This feels inconsistent.

So I agree with you observation, and would accept a PR with makes the inversion fail iff. the determinant is exactly zero for 1D/2D/3D matrices.
