### ISSUE TITLE
why does .dot() require square matrices?

### ISSUE THREAD

**Issue by jonathanstrong** [sebcrozet/nalgebra#257]
I am confused by a requirement on the dot operation for two statically-sized matrix types to have the same number of rows and columns. Dot product of a NxM matrix with am MxP matrix should result in an NxP matrix, but this is impossible given these constraints. Here are some tests to show what I mean (first a reference implementation in ndarray, then the nalgebra one): 

```rust
mod tests {
    #[test]
    fn simple_dot_on_nonsquare_matrices_ndarray() {
        use ndarray::Array2;

        const N: usize = 3;
        const M: usize = 4;
        const P: usize = 3;

        type Matrix = Array2<i32>;

        let a = Matrix::from_elem((N, M), 1);
        let b = Matrix::from_elem((M, P), 2);
        let c = a.dot(&b);
        assert_eq!(c.dim(), (N, P));
        assert_eq!(c, Matrix::from_elem((N, P), 8));
    }

    #[test]
    fn simple_dot_on_nonsquare_matrices_nalgebra() {
        use na::{U3, U4, Matrix, MatrixArray};

        type M3x4i = Matrix<i32, U3, U4, MatrixArray<i32, U3, U4>>;

        type M4x3i = Matrix<i32, U4, U3, MatrixArray<i32, U4, U3>>;

        // what c *should* be
        type M3x3i = Matrix<i32, U3, U3, MatrixArray<i32, U3, U3>>;

        let a = M3x4i::from_element(1);
        let b = M4x3i::from_element(2);
        let c = a.dot(&b);
    }
}
```
The second question I have is, why does `dot` return a scalar rather than a matrix? This is not the behavior I am expecting from experience with other math libraries. What am I missing?

**Comment by sebcrozet** [comment]
`.dot()` does not require square matrices. It requires the inputs to have the same number of rows, and the same number of columns, i.e., both matrices must have the same `NxM` shape.

The dot product implemented in nalgebra is the [scalar product](https://en.wikipedia.org/wiki/Dot_product) of vector spaces (so if the inputs are matrices, they are handled as if they were vectors). Thus, it returns a scalar, not a matrix. I don't know to which libraries your are used to but this is the usual behavior of several popular (C++) linear algebra libraries like Eigen and Armadillo. I believe ndarray uses `dot` for matrix multiplication which can be achieved in nalgebra with the `*` operator.

Also, note that some type aliases already exist for low-dimensional matrices. So instead of redefining, e.g., `M3x4i`, you can use `Matrix3x4<i32>`.

**Comment by jonathanstrong** [comment]
ah, got it. thank you for clarifying. fwiw - in numpy, theano and other Python math libs dot is always matrix multiplication. `na` generally has the best docs of any rust linalg I've been looking at - so may be of note that for someone coming from Python this was not intuitive.

**Comment by sebcrozet** [comment]
Thanks for those details. Actually, I didn't know the Python ecosystem very well (and never heard of theano).

So it looks like there are two different tendencies here. Libraries like ndarray, numpy, and theano that are all n-dimensional (i.e. handle tensors of rank n)  use `dot` as their scalar product for 1D entities, matrix multiplication for 2D, and generalize this to nD.  On the other hand, libraries that focus on vectors and matrices like Eigen, armadillo, nalgebra, only define `dot` for the scalar product only.

I probably should mention this somehow on the doc so that people don't get confused!
