### ISSUE TITLE
Rounding Vectors / Points.

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#276]
Is there a way yet to round vectors or points, similar to `std`'s `round` function implemented for `f32` and `f64`? I cannot seem to find it, but the crate might use a non-standard naming convention, or assume other means of rounding. 

Furthermore, if it is not present, would a `round` function be something to consider? How would we go about adding it, given a rounding operation might not necessarily make sense on any matrix.

**Comment by sebcrozet** [comment]
This is currently not implemented.

Instead of defining a `round` method, it would be more useful to define a method `apply` that takes a closure `Fn(N) -> N` as parameter. Each component is then replaced by the result of the closure (the modification is in-place so this is not a map).

**Comment by Binero** [comment]
Hmm I was about to tinker a bit to resolve this issue but it seems that currently the master branch is broken, as the tests do not compile?

**Comment by sebcrozet** [comment]
Could you paste the error you get please? I've made a fresh clone of the nalgebra repo and test do seem to compile on the master branch.

**Comment by Binero** [comment]
On stable:
```
error: cannot find macro `quickcheck!` in this scope
  --> tests/similarity.rs:15:1
   |
15 | quickcheck!(
   | ^^^^^^^^^^

error: aborting due to previous error(s)
```
On nightly, I get 1096 errors. They all seem to be of the `unused result` variety. 

As for the original issue, wouldn't `apply` be essentially the same as `iter_mut`?

**Comment by sebcrozet** [comment]
Tests and benchmarks can only be computed on nightly because we use `#[feature(test)]` which is unstable. The errors you have on nightly are strange though. Did you enable any features? Could you try with those features enabled:

```
cargo test --features "debug arbitrary serde-serialize"
```

Also, if this still doesn't work, could you try to compile tests on the `linalg` branch?

**Comment by aepsil0n** [comment]
It is a new issue on nightly. I already reported it yesterday in rust-lang/rust#43806. There is already a pull request in, so it should be fixed very soon. For the time being we could comment out the `unused_results` lint perhaps?

**Comment by sebcrozet** [comment]
@aepsil0n Yes, or maybe we could just make it a `warn` instead of a `deny` so that we don't forget to deny it again later.
@Binero I forgot to answer your second question. The `apply` I propose would no be `iter_mut` exactly, but the same as:
```Rust
for e in matrix.iter_mut() {
    *e = f(*e)
}
```
Assuming `f` is a `Fn(N) -> N` where `N` is the scalar type.
I am not sure there exists a clean one-liner way of doing this.
