### ISSUE TITLE
Which trait does Point need to implement?

### ISSUE THREAD

**Issue by gnzlbg** [sebcrozet/nalgebra#288]
I am trying to use my own point type with nalgebra without much luck. Is there a set of traits that it must implement to work with the rest of the library?

**Comment by aepsil0n** [comment]
Most of `nalgebra` uses `alga` for abstraction. There is quite a lot of traits to implement, depending on the functionality you are using.

Perhaps, could you tell a little more about what it is, that you are trying to achieve? In particular, why are you implementing your own point type?

**Comment by gnzlbg** [comment]
> Most of nalgebra uses alga for abstraction. 

I've looked into `alga` but it is not clear to me which traits do I need to implement to have my own Point and Vector type.

> Perhaps, could you tell a little more about what it is, that you are trying to achieve? In particular, why are you implementing your own point type?

I have many types of points in my application, with different types of data stored inside them. I also have a lot of geometric algorithms that can work on n dimensions, and are oblivious of the data. 

So I just want to add whatever constraints are necessary for my data-types, and be able to pass them to nalgebra for the "basic" stuff (dot products and such).

**Comment by sebcrozet** [comment]
> Most of nalgebra uses alga for abstraction.

To be more specific, `nalgebra` uses `alga` for abstracting the scalar type and for abstracting the rotation type for `Isometries` and `Similarities`. It also uses the conversion mechanisms that make the `na::convert` function work. Besides those, `alga` traits are implemented, e.g., for points [there](https://github.com/sebcrozet/nalgebra/blob/master/src/geometry/point_alga.rs) and for vectors [there](https://github.com/sebcrozet/nalgebra/blob/master/src/core/matrix_alga.rs) only to allow the user to do some generic programming. 

Implementing `alga` traits for, e.g., your own vector type, will require you to write an implementation for the dot product. So I am not sure this is what you want to do. Providing a concrete minimal example of actual data type and algorithm signature will help a lot understanding your use-case.

For example, are trying to write an algorithm that takes any type in input provided that they represent points of an n-dimensional euclidean space:

```rust
fn algorithm<P: EuclideanSpace>(a: P, b: P) -> P {
    // Do things with a and b and return a result.
}
```

Or if your want to be able to write an algorith that takes a n-dimensional `Point` from nalgebra, but which contains data you allocated yourself or that has a specific layout (like `Eigen::Map`), e.g., something along the line:

```
fn main() {
    let x_data_source = [ 0; 1000 ];
    let y_data_source = [ 0; 1000 ];
    let point = Point::new(...); // Tell nalgebra that the points does not own its data buffer but has its `x` component stored in `x_data_source` and its `y` component stored in `y_data_source`.
}
```

In the first example I gave, yes, implementing the `alga` traits are necessary.
In the second example, the existing implementation of points on nalgebra needs to be changed in order to be generic wrt. the data storage. Such genericity is already available with vectors, provided that you data storage type implements some traits (at least `Storage`).

**Comment by aepsil0n** [comment]
While it is quite hard to judge your particular use case without seeing details (i.e. code). As a general piece of advice, it may be useful to try to define your custom types as compositions of nalgebra types and whatever you want add on top of that. You may need to add in some conversion for that to work in the beginning. But again, it is hard to judge whether this is applicable to your problem.

**Comment by gnzlbg** [comment]
@aepsil0n I'll try to show some code.

I am writing [fluid dynamics code](https://github.com/gnzlbg/lbm-rs) and am working on its geometry library at the moment.

> As a general piece of advice, it may be useful to try to define your custom types as compositions of nalgebra types and whatever you want add on top of that.

The problem is that:

- I know that different memory layouts will be best for different parts of my application,
- I need these different parts to interface, and
- for the parts of my application for which I don't know the best memory layout, I need the ability to benchmark different layouts without rewriting all my code. 

That is, I need to decouple the memory layout of my geometric primitives from the algorithms that work on them. This is not a new problem, CGAL solved it over a decade ago.

**Comment by aepsil0n** [comment]
@gnzlbg I have not really followed this for a while.

Do you think there are any concrete changes needed to nalgebra for your use case? And has your question about the Point trait been answered sufficiently above?

**Comment by gnzlbg** [comment]
Yes it was helpful, but at the end it turned out that I needed more than just pure linear algebra (needed to deal with floating point errors, among other things) and ended up hand-rolling my own solution.

**Comment by aepsil0n** [comment]
Okay, thanks for the update.
