### ISSUE TITLE
Move types into higher dimensions

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#291]
Is there an easy way to move a type to a higher dimension easily? For example:

```rust
            use na::{Isometry2, Translation2, Unit, Vector2};

            let position_vector =
                position.radius * Vector2::new(position.angle.cos(), position.angle.sin());

            let isometry = Isometry2::new(position_vector.into(), position.angle);
```
Is there an easy way to turn `isometry` into an `Isometry3`?

**Comment by sebcrozet** [comment]
No, this is not possible since we can't predict how the 2D space represented by `Isometry2` is embedded into the 3D space represented by `Isometry3`. For example, should the 2D rotation corresponding to a 2D rotation on the `x,y` plane, the `y,z` plane, or another plane not aligned with any coordinate axis ?

Perhaps we could add a method taking extra arguments (like the normal of the plane on which it is embedded), by I think it is easier for the user to simply do, e.g, `Isometry3::new(iso2.translation.vector, normal * iso2.rotation.angle())`.

**Comment by jswrenn** [comment]
> I think it is easier for the user to simply do, e.g,  `Isometry3::new(iso2.translation.vector, normal * iso2.rotation.angle())`

This doesn't seem quite right. The type of `iso2.translation.vector` will be a `Vector2`, not a `Vector3` (which is what `Isometry3::new` expects as its first argument).

I've been performing this conversion like this:
```
Isometry3::new(
  Vector3::new(isometry2.translation.vector.x,
               isometry2.translation.vector.y, 0.),
  isometry2.rotation.angle() * Vector3::z_axis().to_superset());
```

(If there's a more elegant way to write that first argument, I'd love to hear it.)

**Comment by jswrenn** [comment]
Resolving #304 will address this issue, too.

**Comment by aepsil0n** [comment]
There does not seem to be any further action to take or open questions to answer given #304. Thus closing.
