### ISSUE TITLE
Vector Debug should be more readable

### ISSUE THREAD

**Issue by Boscop** [sebcrozet/nalgebra#295]
Vector's Debug currently looks like this:
`Matrix { data: [1, 0], _phantoms: PhantomData }`

It should be more readable, without PhantomData, because this causes a lot of visual noise when printing arrays of Vectors.

**Comment by aepsil0n** [comment]
I have found that a little annoying, too.

While the standard library provides a derive feature for `Debug`. There does not seem to be any convention, that it should be used though. The only thing I found [in the API guidelines](https://github.com/rust-lang-nursery/api-guidelines/blob/master/src/debuggability.md), said that it should be implemented and non-empty.

From my point of view, there are two main options that make sense:

1. Remove only `_phantoms`: `Matrix { data: [1, 0] }`
2. More radically, reduce it to the array itself: `[1, 0]`

I added the second suggestion, because it would be much more concise for printing small lists of small vectors. To justify: to me `Matrix` seems mostly like a semantic wrapper around the data contained. At the same time its completely transparent what's inside. The downside would be, that you could mix it up with an actual array. I am not sure that is worth avoiding for debug output, though.

cc @sebcrozet

**Comment by Ralith** [comment]
I'd like to see 2; the long multi-line format provided by Display is rarely useful to me, and this would provide a convenient alternative. I expect it would also be easier to implement, as you'd only need to forward to the contained data's existing Debug impl.
