### ISSUE TITLE
Convert a `SliceStorage` to a `MatrixArray` ?

### ISSUE THREAD

**Issue by ChristopherRabotin** [sebcrozet/nalgebra#341]
I have a vector of size `U6` which I need to split in two vectors of size `U3` in order to pass to a function which takes a vector of size `U3`. How can I simply do this? I am currently re-creating a new vector from scratch and passing that, but I suspect there's an easier way.

For clarification, here is the signature of the function which I am attempting to call:
```
fn largest_step(prop_err: &VectorN<f64, U3>, state_delta: &VectorN<f64, U3>) -> f64
where
    DefaultAllocator: Allocator<f64, U3>, { /* ... */ }
```

And here's how I tried calling it:
```
fn largest_step_pos_vel(prop_err: &VectorN<f64, U6>, state_delta: &VectorN<f64, U6>) -> f64
where
    DefaultAllocator: Allocator<f64, U6>,
{
    let err_radius = largest_step(
        &prop_err.fixed_slice::<U3, U1>(0, 0),
        &state_delta.fixed_slice::<U3, U1>(0, 0),
    );
    let err_velocity = largest_step(
        &prop_err.fixed_slice::<U3, U1>(3, 0),
        &state_delta.fixed_slice::<U3, U1>(3, 0),
    );
    /* ... */
}
```

The compilation error is the following:

```
error[E0308]: mismatched types
  --> src/propagators/error_ctrl.rs:65:9
   |
65 |         &state_delta.fixed_slice::<U3, U1>(3, 0),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `propagators::na::MatrixArray`, found struct `propagators::na::SliceStorage`
   |
   = note: expected type `&propagators::na::Matrix<f64, propagators::na::U3, propagators::na::U1, propagators::na::MatrixArray<f64, propagators::na::U3, propagators::na::U1>>`
              found type `&propagators::na::Matrix<f64, propagators::na::U3, propagators::na::U1, propagators::na::SliceStorage<'_, f64, propagators::na::U3, propagators::na::U1, propagators::na::U1, propagators::na::U6>>`

```

**Comment by sebcrozet** [comment]
You need to call `.into_owned()` to convert a slice (which does not own its data) into a plain vector that owns its data. So in your case for example `prop_err.fixed_slice::<U3, U1>(0, 0).into_owned()`. There is also `.clone_owned()` if you don't want to move the slice. That makes me think that it might be worth considering adding an implementation of `Into` that has the same effect as `.into_owned()`!

In addition, note that your code could be simplified in a few ways if you want:
1. You may use vector type aliases instead of `VectorN`. For example `Vector3<f64>` instead of `VectorN<f64, U3>` and `Vector6<f64>` instead of `VectorN<f64, U6>`.
2. You don't need to add the trait bound `DefaultAllocator: Allocator<f64, U6>`. This is needed only when the dimension of the vector (or matrix) is given as an abstract type parameter.
3. Because a vector is a column vector, it has one column and several rows. So instead of `.fixed_slice::<U3, U1>(3, 0)`, you may use the simpler method `.fixed_row::<U3>(3)`. You can see [this](http://nalgebra.org/vectors_and_matrices/#matrix-slicing) for some details.

With all those modifications, your code would look like this:

```rust
fn largest_step(prop_err: &Vector3<f64>, state_delta: &Vector3<f64>) -> f64
{ /* ... */ }

fn largest_step_pos_vel(prop_err: &Vector6<f64>, state_delta: &Vector6<f64>) -> f64 {
    let err_radius = largest_step(
        &prop_err.fixed_rows::<U3>(0).into_owned(),
        &state_delta.fixed_rows::<U3>(0).into_owned(),
    );
    let err_velocity = largest_step(
        &prop_err.fixed_rows::<U3,>(3).into_owned(),
        &state_delta.fixed_rows::<U3>(3).into_owned(),
    );
    /* ... */
}
```

**Comment by ChristopherRabotin** [comment]
Thanks plenty! I knew there must have been a simpler way to extract these items! ;-)
