### ISSUE TITLE
Cholesky f32 f64

### ISSUE THREAD

**Issue by nilgoyette** [sebcrozet/nalgebra#348]
I have a square 45x45 matrix `A` and vector `b`, and I use Cholesky to find `x`, for the problem `Ax = b`. For performance reasons, all my data is in f32. In some very rare cases, `a.cholesky()` returns `None`.

The documentation says `Returns None if the input matrix is not definite-positive.` Unsure what this means, I tested other things :) When I cast my data to f64 (exactly the same matrix, but in f64), cholesky succeeds.

This behavior is really surprising to me. I'm not a mathematician, but I would have thought that if a f32 matrix is not definite-positive, the same matrix in f64 should have the same properties. Is this normal?

**Comment by sebcrozet** [comment]
Do you have an example of such a matrix? It would help determining if this is a bug or if it is expected.

A matrix `A` is "definite-positive" iff for any non-zero vector `x`, we have `transpose(x) A x > 0`. In other word, if you seen the matrix `A` as a transformation, this means `A` does not rotate `x` by more than 90 degrees (and scales its length by a factor strictly greater than 0).

There may be some rare cases where the 64-bit Cholesky execution succeeds but  the 32-bit does not. Those cases are for example:
- The matrix is close no being not definite positive. Then, because 32-bit floats are subject to more severe rounding errors, it may end up thinking the matrix is not definite positive while the 64-bit works fine. In practice this means that at some point, the Cholesky decomposition computes a square root. Because of rounding errors, a number that ends up close to zero in 64-bits (obtained by some intermediate computations) may actually end up negative in 32-bits, which means Cholesky fails only on the latter case. 
- The matrix contains very large elements as well as very small ones. Again, because of rounding errors, intermediate computations may fail on the 32-bit version but yield a valid result in 64-bit.

In those rare cases where the Cholesky decomposition fails, you may use the LU decomposition instead which will work as long as your matrix can be inverted.

**Comment by nilgoyette** [comment]
Yes, I have a 45x45 matrix that fails on Cholesky but I don't really want to copy it here. The first 4x4 elements looks like

    7441617.0,   -57466.082, -15802.126,  -27951.113, ...
     -57466.082, 237381.6,     3317.194,   37901.86, ...
     -15802.126,   3317.194, 129217.85,      548.4954, ...
     -27951.113,  37901.86,     548.4954, 179759.75, ...
    ...

The rest of the matrix looks somewhat like that. Is this what you mean by `very large elements as well as very small ones`? I thought it was "small" in the sense of "really close to 0.0" but I checked and it's not the case here.

**Comment by sebcrozet** [comment]
By "very small" I meant values close to 0.0 as you guessed. Though it appears the entries of your matrix are quite large which is problematic since float computations with large values are much less accurate than with values close to zero. So there is a great change this explains why Cholesky sometimes behaves worse with f32 than with f64.

**Comment by nilgoyette** [comment]
Well, ok, I guess there's not much to do about it :) I'll simply use f64. Thank you for your time.
