### ISSUE TITLE
nalgebra 0.15.3 won't compile for wasm32-unkown-unkown

### ISSUE THREAD

**Issue by arturoc** [sebcrozet/nalgebra#357]
Seems like one of the dependencies, rand 0.5.1 doesn't compile under wasm32:

```
Compiling rand v0.5.1
error[E0433]: failed to resolve. Use of undeclared type or module `imp`
   --> /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.5.1/src/rngs/os.rs:118:18
    |
118 | pub struct OsRng(imp::OsRng);
    |                  ^^^ Use of undeclared type or module `imp`

error[E0433]: failed to resolve. Use of undeclared type or module `imp`
   --> /home/arturo/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.5.1/src/rngs/os.rs:129:9
    |
129 |         imp::OsRng::new().map(OsRng)
    |         ^^^ Use of undeclared type or module `imp`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `rand`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by arturoc** [comment]
seems it's something they introduced in 0.5.1, fixing the version at 0.5.0 works. In Cargo.toml:

```toml
rand           = { version = "=0.5.0", default-features = false }
```

**Comment by arturoc** [comment]
ah ok, thanks!

**Comment by estatistics** [comment]
" Compiling nalgebra v0.16.0
   Compiling cssparser v0.24.0
error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
   --> /home/elias/Downloads/librsvg-2.44.0/vendor/cssparser/src/parser.rs:572:17
    |
547 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
    |                                                   - let's call the lifetime of this reference `'1`
...
560 |             Some(ref cached_token)
    |                  ---------------- borrow of `self.input.cached_token` occurs here
...
572 |                 self.input.cached_token = Some(CachedToken {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
...
584 |         Ok(token)
    |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0506`.
error: could not compile `cssparser`.
"

**Comment by sebcrozet** [comment]
@estatistics Hi! Please open a new issue, this one is already closed and your issue does not involve nalgebra 0.15.3 mentioned on this issue's title. The error you are getting is caused by `cssparser`, not nalgebra, so you probably should open an issue on [their repository](https://github.com/servo/rust-cssparser).
