### ISSUE TITLE
Mat4 look_at function

### ISSUE THREAD

**Issue by bjz** [sebcrozet/nalgebra#44]
Is there an equivalent to cgmath's [`Matrix4::look_at` function](http://rust-ci.org/bjz/cgmath-rs/doc/cgmath/struct.Matrix4.html#method.look_at)?

~~~rust
fn look_at(eye: &Point3<S>, center: &Point3<S>, up: &Vector3<S>) -> Matrix4<S>
~~~

**Comment by aepsil0n** [comment]
Your perspective projection is not only transposed as compared to PistonDevelopers/cam, but also has a different sign in two places. Is this due to different handedness, too?

**Comment by tyoc213** [comment]
A little off topic, but I also don't want to open an extra ticked for ask this I'm following https://open.gl/transformations and on the part **A simple transformation** they use some like

```
glm::mat4 trans;
trans = glm::rotate(trans, glm::radians(180.0f), glm::vec3(0.0f, 0.0f, 1.0f));

glm::vec4 result = trans * glm::vec4(1.0f, 0.0f, 0.0f, 1.0f);
printf("%f, %f, %f\n", result.x, result.y, result.z);
```

I have used 

```
let a = Vec3::new(0.0, 0.0, 0.5 * mypi);
    let mut ro = Rot3::new(na::zero());
    ro.append_rotation_mut(&a);

    let rotMat = na::to_rot_mat(&ro);
```


If I wanted to do exactly the "same" procedure, how I will achieve it?

Also I have found that if I wanted to create a rot4 I will use 2 quaternions? https://github.com/sebcrozet/nalgebra/pull/74 but from https://github.com/sebcrozet/nalgebra/blob/44df67bde2875eba733a2580d10f15e455cdd23d/src/structs/rot.rs#L349 it seem commented out?

Also I see that there are some panics, thought nobody has asked or run in them for those implementations, you could use ```std::unimplemented!``` or do like https://github.com/sebcrozet/nalgebra/pull/141

Also an extra question, I feel my question is not an issue to make a new ticket... so, where I should ask for help when I'm stuck?

**Comment by sebcrozet** [comment]
`Rot4` is definitely not what you want to use here. `Rot4` is a rotation on a 4-dimensional space where what you want is a rotation in 3D euclidean space (the "regular" one). The problem here comes from an usual confusion due to simplifications (on the math-theoretical side) most computer-graphics-related tutorials often make.

One should make the distinction between an actual rotation in 3D space and in 3D projective space. The first one is usually represented as a 3x3 orthogonal matrix with determinant 1 while the second one is a 4x4 matrix but with its last row and column set to 0 except for its last entry (which is set to one). So the computations you are trying to reproduce here (using `glm::mat4`) are preformed in projective space instead of the regular one.

In `nalgebra` structures like `Rot3`, `Vec3` and `Pnt3` live in the regular 3D space so transforming `Rot3` to a matrix will give you a 3x3 matrix. If you want to obtain its analogous in 3D projective space, you have to perform a conversion using the `::to_homogeneous(...)` function (named after the concept of _homogeneous coordinates_ you have probably encountered already). You can call this function on a `Vec3` or `Pnt3` as well to get 4D vectors with its last entry set to 0 or 1 respectively. In other words, the path from euclidean space to the projective space is the `na::to_homogeneous(...)` function while the reverse operation is the `na::from_homogeneous(...)` function.

There are two ways to reproduce the example you cited:
```rust
glm::mat4 trans;
trans = glm::rotate(trans, glm::radians(180.0f), glm::vec3(0.0f, 0.0f, 1.0f));

glm::vec4 result = trans * glm::vec4(1.0f, 0.0f, 0.0f, 1.0f);
printf("%f, %f, %f\n", result.x, result.y, result.z);
```

The first option is to simply perform all your operations in the regular 3D space:
```rust
let trans = Rot3::new(Vec3::new(0.0f32, 0.0, 0.5 * mypi));
let result = trans * Pnt3::new(1.0f32, 0.0, 0.0);
println!("{:?}", result); // Displays a Pnt3.
```

The second option is to perform all your operations in the 3D projective space:
```rust
let trans = Rot3::new(Vec3::new(0.0f32, 0.0, 0.5 * mypi));
let projective_trans = na:.to_homogeneous(&trans.to_homogeneous); // obtain a Mat4
let pt = Pnt3::new(1.0f32, 0.0, 0.0);
let projective_pt = na::to_homogeneous(&pt); // obtain a Vec4
let result = projective_trans * projective_pt; // obtain a Vec4
println!("{:?}", result); // Displays a Vec4.
```

To go further, I guess you might want to use a combination of rotation and translation later. Such combination is done by the `Iso3::new(translation, rotation)` function. As usual, its analogous into projective space is obtained with `na::to_homogeneous(...)` and you will obtain a 4x4 matrix arranged just like the description given on the tutorial you pointed to.

> Also an extra question, I feel my question is not an issue to make a new ticket... 
> so, where I should ask for help when I'm stuck?

Currently, opening an issue or sending me a mail directly are unfortunately the ways to go. I intend to open a forum at some point in the near future.

> Also I see that there are some panics, thought nobody has asked or run in them for those implementations, you could use std::unimplemented! or do like #141

You're right, I should use `std::unimplemented!` there. Well spotted!

**Comment by tyoc213** [comment]
Thanks for the help!
